### ISSUE TITLE
[FEATURE REQUEST] IFTTT Webhook Notification

### ISSUE THREAD

**Issue by DJay-X** [potrudeau/homebridge-messenger#1]
@potrudeau  First of all thanks for your work on this plugin and sharing with the community. 🙏

At them moment I am using [homebridge-notification](https://github.com/sergeturgeon/homebridge-notification)Plugin to get Notifications pushed to show in a fancy way that something was triggert. See Screenshot.
Unfortunately the plugin is not maintained since 3 years and I got the impression that is not working properly anymore. Im using 26 of this "build" notifications.

![Napkin 23 04 20, 1 44 02 PM](https://user-images.githubusercontent.com/3874239/80095623-86083800-8568-11ea-9612-839ebfcc61f4.png)

Do you see a way to integrate IFTTT Notification also to your messenger as a service?

With homebridge-notification the config looks like this

```
{
            "accessory": "Notification",
            "name": "Notify Wasserkocher ein",
            "ifttt_api_key": "xxxxxxxxxxxxxx",
            "ifttt_event": "Kettle_on_03",
            "ifttt_message": "Wasserkocher ist eingeschaltet",
            "ifttt_mute_notification_interval_in_sec": 10
        },
```

It triggers a Webhook to IFTTT and the IFTTT App is then pushing a rich notification including an Image.

Thanks in advance for the time you invest and for your consideration.

![Napkin 23 04 20, 1 36 01 PM](https://user-images.githubusercontent.com/3874239/80095383-1eea8380-8568-11ea-88dc-aaa924ac3d6d.png)

**Comment by potrudeau** [comment]
IFTTT was always planned for this plugin! I should be available over the new few days.

The code is written and I'm currently testing. The last step before releasing is implemeting the Homebridge Plugin Settings GUI.

I will close this issue when the new version (0.0.5) will be released. ;)

**Comment by DJay-X** [comment]
Wow. Thanks for your fast reply and the positive feedback. This is awesome. Thank you so much.
Then I can finally switch to your plugin and still get richt text notifications including picture with IFTTT. 👍 

However, is it also possible to use Pushover and include an image directly with your plugin right now?

Something like 
```
"messages": [
              {
                  "type": "pushover",
                  "name": "Pushover message",
                  "text": "This is a test",
                  "sound": "pushover",
                  "device" : "iPhone",
                  "image" : "https://i.imgur.com/edPcUfc.png",
                  "priority": 0
              },
```

Anyway, thanks again for your support and the time you are investing.

**Comment by potrudeau** [comment]
Pushover does not have an image property. But it could send HTML messages. I haven't implemented this but it could be done. Your texte could then have an html img in it.

**Comment by potrudeau** [comment]
IFTTT is now implemented. You can now use it, or use Pushover! ;P

**Comment by DJay-X** [comment]
Thanks @potrudeau 
Can I use Pushover and IFTTT configured in the same config.json? 🤔

**Comment by DJay-X** [comment]
Figured it our. 😬

```
{
            "name": "Messenger",
            "services": {
                "pushover": {
                    "user": "xxxxxxx",
                    "token": "xxxxxx"
                },
                "ifttt": {
                    "key": "xxxxxxxx"
                },
                "email": {
                    "smtpPort": 8080
                }
            },
            "messages": [
                {
                    "name": "Test IFTTT",
                    "type": "ifttt",
                    "event": "mikettle_done",
                    "value1": "Der Wasserkocher ist fertig.",
                    "value2": "Zeile 2",
                    "value3": "Zeile 3"
                },
                {
                    "name": "Test-Pushover-Messages",
                    "type": "pushover",
                    "text": "<img scr='https://i.imgur.com/edPcUfc.png'>",
                    "device": "iPhone11Pro",
                    "priority": 0,
                    "sound": "pushover"
                },
                {
                    "name": "Test2-Pushover-Messages",
                    "type": "pushover",
                    "text": "This is only a test",
                    "device": "iMac,iPhone11Pro",
                    "priority": 0,
                    "sound": "pushover"
                }
            ],
            "accessory": "HomebridgeMessenger"
        }
```

**Comment by potrudeau** [comment]
Good! 👍 

FYI, I have a full example available [here](https://github.com/potrudeau/homebridge-messenger/blob/master/configuration-examples/advanced.example.json).
