### ISSUE TITLE
Feature Request: Multiple Email Recipients

### ISSUE THREAD

**Issue by typkrft** [potrudeau/homebridge-messenger#13]
I may have missed something, but this would be a great feature to add to an already fantastic module.

**Comment by siobhanellis** [comment]
Have you tried a comma separated list. I looked at the dependancies and that says you can do it.

**Comment by siobhanellis** [comment]
I tested it. comma separated works. However, it does suggest in the UI that there is an error in configuration... but it'll save it anyway.

**Comment by potrudeau** [comment]
@typkrft :
Feature was added in version 0.0.7. Please see documentation for further details: 
https://github.com/potrudeau/homebridge-messenger/#email

It's published and available now.
