### ISSUE TITLE
Feature request: Alternate email address override

### ISSUE THREAD

**Issue by siobhanellis** [potrudeau/homebridge-messenger#14]
It would be good if we had a default destination email ddress, basically what you have now. Also an override in a message.

This would mean that all messages would go to default, except where explicitly overriden.

Thanks

**Comment by potrudeau** [comment]
@siobhanellis : 
Feature was added in version 0.0.7. Please see documentation for further details: 
https://github.com/potrudeau/homebridge-messenger/#email

It's published and available now.
