### ISSUE TITLE
E-mail error

### ISSUE THREAD

**Issue by Ghitafjorback** [potrudeau/homebridge-messenger#16]
Hi

Love what this plugin should be possible of, but I can't seem to get the email option to work. I have tried several different smtp servers as I have multiple email addresses, I tried both with Secure on and off, but I keep getting below error, and Homebridge will crash!? ![image](https://user-images.githubusercontent.com/59295827/100937608-89e33c00-34f3-11eb-8ac3-a38663628e67.jpeg)

**Comment by potrudeau** [comment]
This is bug. I'm getting the same thing. I will be looking into this!

**Comment by potrudeau** [comment]
This is a duplicate of issue #15.
I will close this.
Thanks!
