### ISSUE TITLE
Got SIGTERM, shutting down Homebridge... when Error: application token is invalid

### ISSUE THREAD

**Issue by DJay-X** [potrudeau/homebridge-messenger#2]
Thanks to your new discovered plugin I'm trying to also play around Pushover.
I noticed that homebridge is crashing when the token is invalid.
Maybe not the whole homebridge should stop working and crash in such a case?

Thanks in advance. Love that I have found your project.

```
Apr 23 15:34:57 raspberrypi-3BPlus homebridge[6416]: [2020-4-23 15:34:57] [Messenger] Test-Pushover-Messages : Message sent to xxxxxxxxx
Apr 23 15:34:57 raspberrypi-3BPlus homebridge[6416]: [2020-4-23 15:34:57] Error: application token is invalid
Apr 23 15:34:57 raspberrypi-3BPlus homebridge[6416]:     at Pushover.errors (/usr/local/lib/node_modules/homebridge-messenger/node_modules/pushover-notifications/lib/pushover.js:83:12)
Apr 23 15:34:57 raspberrypi-3BPlus homebridge[6416]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-messenger/node_modules/pushover-notifications/lib/pushover.js:167:11)
Apr 23 15:34:57 raspberrypi-3BPlus homebridge[6416]:     at IncomingMessage.emit (events.js:322:22)
Apr 23 15:34:57 raspberrypi-3BPlus homebridge[6416]:     at endReadableNT (_stream_readable.js:1187:12)
Apr 23 15:34:57 raspberrypi-3BPlus homebridge[6416]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Apr 23 15:34:57 raspberrypi-3BPlus homebridge[6416]: [2020-4-23 15:34:57] Got SIGTERM, shutting down Homebridge...
```

**Comment by DJay-X** [comment]
And I have problems to identify what my "user" and "token" is?

When I go over to https://pushover.net and login, I did "Create a New Application". I received a API Token/Key like "ab34cd78ef12gh56ij90kl34mn78op"
I assume this is to put in the config under `"token": "ab34cd78ef12gh56ij90kl34mn78op"`.
But what do I have to use for `"user": "xxxx",`? Obviously it's not my E-Mail I login to Pushover.

Unfortunately I can't anything in the readme instructions here. 

Thx.

**Comment by potrudeau** [comment]
To be honest, it's _as designed_. 
If Pushover or any other service is not able to send the message, it raises an error.  The goal for this is to tell you that something is wrong. That being said, I will try and find an improvement on this. Homebridge doesn't have any warning mecanism.

**Comment by DJay-X** [comment]
Saying that, this does make sense. 😅 
`"user":` = User Key from Dashboard
`"token":` = Create a New Application, API Token/Key

Thanks you. 🙈 Works now.

If you are willing and it is possible to implement `url` and `attachment` Pushover seems to be a great alternative for IFTTT Notification maybe. At lease another option.

**Comment by potrudeau** [comment]
URL is possible. So is sending HTML messages. 

Attachment would probably require to add a file upload fonction. See [pushover API](https://pushover.net/api#attachments). That doesn't seem like a good idea.

**Comment by DJay-X** [comment]
I thought it would maybe possible to grab the image from an URL like IFTTT is doing it. 

I use the URL for URL-Scheme to open with the Push an Application like evehome:// or HomeConnect:// 

May you move me over to your plugin by finding some equal features. :) 

By the way, I miss your PayPal or BuyMeACoffee link. ;) 

Thanks a lot. I appreciate you work and the friendly contact.

**Comment by potrudeau** [comment]
IFTTT is a bit different than Pushover. The APIs are not the same. However, Pushover is faster and more reliable.  You could have an image in HTML format like this in your message. That will work once the HTML property will be added.

![2020-04-23 10_40_52-Homebridge-Dev](https://user-images.githubusercontent.com/1062160/80112346-015cf000-854f-11ea-8c90-c34296a978f0.png)

**Comment by DJay-X** [comment]
That looks perfect to me. Main thing is to insert a custom url to point to the image. And the Image is showing up in the notification like in the example.
![80095383-1eea8380-8568-11ea-88dc-aaa924ac3d6d](https://user-images.githubusercontent.com/3874239/80113505-b230b280-8582-11ea-8a0c-dccad86ebc3f.png)
An click on "View", I think in Pushover it's "Open URL" would open what is under "url": evehome://

👍

**Comment by potrudeau** [comment]
URL and Message will be added when issue #3 will be completed. It will used Pushover's features. 
It **should** work like you wish (but it's not related to plugin, but how Pushover works).

I will close this issue.
