### ISSUE TITLE
[FEATURE REQUEST] Pushover HTML and URL properties

### ISSUE THREAD

**Issue by potrudeau** [potrudeau/homebridge-messenger#3]
As discussed in issue #2 and asked by @djay-x, the following properties should be added to the plugin for Pushover messages:

- HTML
- URL
- URL Title

**Comment by potrudeau** [comment]
@DJay-X : I've added the HTML. However, the Pushover API doesn't want to include img for some reason. It doesn't look to be supported. For you needs, I think it will be easier to use the IFTTT Webhook.

**Comment by potrudeau** [comment]
Done.

**Comment by DJay-X** [comment]
Thanks a lot. Thats of course a shame that the API doesn't want to include img. :(
Like you probably already did, I'll send a support question to the Pushover Team and ask for it or why this is not working. 
Thanks again to you.

**Comment by potrudeau** [comment]
I opened a ticket this morning. 
I'll keep you informed if something changes.

**Comment by potrudeau** [comment]
Pushover confirmed we cannot send inline images. 
We must use attachment and that's not an option with Homebridge.

So, case close... 👎

**Comment by DJay-X** [comment]
Here also the reply. 😕


> 28. April 2020 um 17:25:13 MESZ Pushover Support <support@pushover.net>:
> Hi, we do not have any immediate plans to support inline HTML images.
> 
> 26 Apr 2020 at 20:57:47 +0200, DJay wrote:
> Thanks for your reply.
> And any plans to do so? ;)
> All the best to you.
> Daniel
> 
> 26.04.2020 20:13 Pushover Support <support@pushover.net>:
> Hi, it is not possible to use inline images with HTML formatting.

**Comment by potrudeau** [comment]
> Here also the reply. 😕
> 
> > 1. April 2020 um 17:25:13 MESZ Pushover Support [support@pushover.net](mailto:support@pushover.net):
> >    Hi, we do not have any immediate plans to support inline HTML images.
> > 
> > 26 Apr 2020 at 20:57:47 +0200, DJay wrote:
> > Thanks for your reply.
> > And any plans to do so? ;)
> > All the best to you.
> > Daniel
> > 26.04.2020 20:13 Pushover Support [support@pushover.net](mailto:support@pushover.net):
> > Hi, it is not possible to use inline images with HTML formatting.

👎
