### ISSUE TITLE
[BUG] "device": multiple devices using a comma

### ISSUE THREAD

**Issue by DJay-X** [potrudeau/homebridge-messenger#4]
You are pointing to..
- device (facultative): The device name to send the message to. If not specified, the message will be send to all your devices. You can send to multiple devices by using a coma.

I tried 

```
{
                    "name": "Test2-Pushover-Messages",
                    "type": "pushover",
                    "text": "This is only a test",
                    "device": "iMac, iPhone11Pro",
                    "priority": 0,
                    "sound": "pushover"
                }
```

I noticed that the separation by comma is not having an effect. Only the first device is getting a push message. I tried vice versa. Always the the first one.
However, when I leave it blank, both devices get a notification.

I hope this is a bug I found and not something to bother you. :) Thx.

**Comment by potrudeau** [comment]
I will investigate.

**Comment by potrudeau** [comment]
If you remove the space between the comma and your iPhone. Like this:
![image](https://user-images.githubusercontent.com/1062160/80130101-12fdc200-8566-11ea-869c-b6b2cff1f075.png)

That seems to work for me. If it also work for you, I will add some code to remove the spaces before calling the Pushover API.

**Comment by DJay-X** [comment]
You are absolutely right. With no space between the comma it worked as well.
Who knows why I intuitively placed a space after a comma? :)

**Comment by potrudeau** [comment]
It looks better! ;)
I'll add some code to remove all spaces. This will solve the issue for everyone.

**Comment by potrudeau** [comment]
Please update your plugin. This is fixed.
