### ISSUE TITLE
Deleting a switch changes the id

### ISSUE THREAD

**Issue by raixer** [potrudeau/homebridge-messenger#9]
I came across an issue a few days ago. I deleted the first switch I created. This made all the other switches adopt a different id and thus the automations became shuffled around. I had to go to each automation and change it to the correct switch.
Please make it so that the id isn’t dependent on the position in the list. Which is what I think is happening. 
Perhaps doing a platform instead of an accessory helps in this case.

**Comment by potrudeau** [comment]
I think your right.
But changing this would maybe break all the automation for everyone. I will investigate the issue.

**Comment by permaMonk** [comment]
This happens also to me several times under configuration change process. And this above would be a good explanation.
